### ISSUE TITLE
视频尺寸96mb，传送失败

### ISSUE THREAD

**Issue by Yumega** [LANDrop/LANDrop#16]
从win10传96mb的视频到苹果手机，每次传60mb就失败了，实验多次都不成功。

**Comment by yvbbrjdr** [comment]
Try upgrading the iOS App.

**Comment by Yumega** [comment]
> Try upgrading the iOS App.

就是今天升级后出现的问题

**Comment by yvbbrjdr** [comment]
What's the error message. Do you have screenshots?

**Comment by Yumega** [comment]
> What's the error message. Do you have screenshots?

重启电脑又可以了
