### ISSUE TITLE
LANDrop Windows Desktop V2.0 Conflict With Clash for WIndows

### ISSUE THREAD

**Issue by Cheeesse** [LANDrop/LANDrop#184]
LANDrop Windows Desktop V2.0
Clash for WIndows V0.20.39

When sending file to other device, shows "The proxy type is invaild for this operation". Must turn off Clash to slove this issue.
Warning screenshot shows below:
![image](https://github.com/LANDrop/LANDrop/assets/18539398/28a1ae6e-a49a-4947-b8b4-49883b9526b9)

**Comment by yvbbrjdr** [comment]
Noted. Will fix in the next version

**Comment by yvbbrjdr** [comment]
Fixed!
