### ISSUE TITLE
IOS客户端无法使用LanDrop v2.0 共享

### ISSUE THREAD

**Issue by mochamapleaf** [LANDrop/LANDrop#185]
之前我的工作流是将notebility的pdf通过“共享”功能直接使用landrop发送。更新到v2.0之后"共享“中Landrop的选项消失了。现在只能先保存到本地文件，再使用landrop上传

**Comment by yvbbrjdr** [comment]
你好！现在的版本应该还是支持共享的。在app列表右边的“更多”里找找？

**Comment by PIndividual** [comment]
我也一样。不仅共享列表里landrop的选项消失了，iOS设备根本不能发现Windows客户端了，同时Windows端也经常出现卡死，后台高资源占用但是不显示窗口等问题。现在这个在不同设备间互相传文件的方法对我已经彻底坏掉了！请重新上架iOS端老版本的landrop，或者拜托拜托给个ipa，我自己侧载也行。新版根本不能用
![image](https://github.com/LANDrop/LANDrop/assets/62368342/1105bea5-3c76-4e6e-9434-abff1ce08d67)

**Comment by yvbbrjdr** [comment]
请问是否在设置中给LANDrop网络权限？在下个更新我们将解决这个问题。

**Comment by yvbbrjdr** [comment]
![image](https://github.com/LANDrop/LANDrop/assets/8556301/cb2c16f5-d99b-4b68-a29d-6c4fa9a81ef5)

**Comment by PIndividual** [comment]
这个菜单里是完全找不到landrop的选项的。我还在iOS15，这也可能和iOS版本有关

**Comment by mochamapleaf** [comment]
给了网络权限，共享菜单里也没有，我的是iPad IOS 15.1，或许应该是IOS版本的问题咯

**Comment by yvbbrjdr** [comment]
这个问题已经修复。会在iOS版本2.1.1推送过来。

**Comment by djdanielchan** [comment]
> 这个问题已经修复。会在iOS版本2.1.1推送过来。
一样不行,pc端是2.3.2  ios端是2.4.1
