### ISSUE TITLE
完全崩坏的新版本

### ISSUE THREAD

**Issue by PIndividual** [LANDrop/LANDrop#186]
将iOS和Windows端更新到2.1后iOS端无法再次发现Windows客户端了，这意味着我无法从手机传送任何文件到Windows。同时iOS端一旦上线，Windows端会立刻开始未响应，除此之外也经常出现landrop在托盘中的图标点不动，不显示窗口的情况。现在这个多端文件传输的方案已经完全不能用了。
在Windows端我可以通过GitHub找到老版本（0.4），但是iOS端我完全找不到landrop老版本的安装途径了。请开发者上架老版本，或者将iOS安装包（ipa）公开出来，我宁可顶着7天一刷新的限制自签也不能失去这个软件😭
![image](https://github.com/LANDrop/LANDrop/assets/62368342/71b5dcf7-9fca-4672-99a4-935e8ffa61d3)

**Comment by PIndividual** [comment]
![image](https://github.com/LANDrop/LANDrop/assets/62368342/cebdd1a5-46ff-49e3-ae92-64951e1a0ba1)

**Comment by yvbbrjdr** [comment]
请问是否在设置中给LANDrop网络权限？在下个更新我们将解决这个问题。

**Comment by PIndividual** [comment]
权限是肯定给了的，但是就是发现不了Windows设备，同时我注意到Windows端只要iOS端一上线就会卡死，当iOS端锁屏或者把landrop划掉之后才能正常。

**Comment by PIndividual** [comment]
我有个猜测，这可能和我的iOS版本有关系，我因为个人原因需要留在iOS15，或许iOS15根本没有完善的multicast支持，因为另一个局域网传文件的app：local send在我的设备上也是根本不能发现Windows端的，只有老版本的landrop在这里用的非常舒服

**Comment by yvbbrjdr** [comment]
能否更新到最新版本试试看。现在应该没问题了。

**Comment by xmover** [comment]
> 我有个猜测，这可能和我的iOS版本有关系，我因为个人原因需要留在iOS15，或许iOS15根本没有完善的multicast支持，因为另一个局域网传文件的app：local send在我的手机上也是根本不能发现Windows端的，只有老版本的landrop在这里用的非常舒服

所以……新版本和老版本代码有何不同吗？

**Comment by yvbbrjdr** [comment]
问题在最新版iOS版本2.5.1上修复了
