### ISSUE TITLE
Feature suggestion: add to share sheet on iOS

### ISSUE THREAD

**Issue by shanejs** [LANDrop/LANDrop#20]
As a user, I would like to be able to send files by using the standard iOS share sheet. For example, if I am in the photos app:

1. Select photo
2. Click the share icon
3. Select LANDrop app
4. A window would appear allowing me to select the destination device

The next time I do this, the last device selected would be default.

Please see example from Discord

![image](https://user-images.githubusercontent.com/184801/121772116-54657e00-cb28-11eb-9865-25686bafbf19.png)

**Comment by yvbbrjdr** [comment]
The iOS app already has this feature. Try selecting multiple pics and find LANDrop in the list. Idk why it doesn't work some time though..
