### ISSUE TITLE
Landrop 2.4.0 GUI is not working. Receiving files still works, but not sending.

### ISSUE THREAD

**Issue by TheOtherGuy** [LANDrop/LANDrop#209]
As titled, when I open Landrop app in my Mac running Mac OS Sonoma, the GUI does not appear.
However, I can see it listed in Activity Monitor.

I can see my Mac from another PC's Landrop and send files to my Mac, but I am unable to send file from my Mac to any other PC as the GUI does not appear. 

Is anyone facing this issue? Thanks!

**Comment by yvbbrjdr** [comment]
LANDrop runs in your task bar

**Comment by TheOtherGuy** [comment]
Oh another app was hiding Landrop in the Menu Bar. I found it and was able to access the GUI. 
Thanks for the reply!
