### ISSUE TITLE
[Android] Why does the app need location access?

### ISSUE THREAD

**Issue by pitsi** [LANDrop/LANDrop#211]
I got the upgrade to 2.7.0 earlier (I was on 2.5.x, if not older, before that) and upon launching the app, it asked me for location access. Why does it need to access my location?

**Comment by yvbbrjdr** [comment]
It's actually for Bluetooth to be able to detect nearby devices. Somehow Google requires location for this to work.

**Comment by pitsi** [comment]
Does it now use bluetooth (too) to share files?

**Comment by yvbbrjdr** [comment]
It uses Bluetooth to discover other devices, but still uses Wi-Fi to transfer the files.

**Comment by pitsi** [comment]
I see. Like nearby share, which I hate for that reason. Thank you for the clarification.
Good thing landrop works without bluetooth and location access though.
