### ISSUE TITLE
socketexception software caused connection abort

### ISSUE THREAD

**Issue by bbggkk** [LANDrop/LANDrop#214]
![Screenshot_2024-09-16-08-16-37-299_app landrop la](https://github.com/user-attachments/assets/3c29482c-8f49-4eb7-9d18-f50de895dfcd)

电脑传手机可以，手机传电脑不行，提示如图。
ios设备正常
另外一台安卓手机正常，
可以确定是这台手机问题，只是报错这台是日常用机，可否有排查办法？
重装app，清除cache都试过了，没用
难道小米的澎湃os有什么反人类的系统级参数和landrop冲突？

**Comment by yvbbrjdr** [comment]
有没有类似防火墙或者软件权限之类的问题？

**Comment by bbggkk** [comment]
> 有没有类似防火墙或者软件权限之类的问题？

![Screenshot_2024-09-22-16-24-02-443_com.miui.securitycenter.jpg](https://github.com/user-attachments/assets/75b1e9a4-d9e5-477c-8c06-c39e99f6980c)

![Screenshot_2024-09-22-16-24-12-478_com.miui.securitycenter.jpg](https://github.com/user-attachments/assets/edc123d3-e638-44d8-8f80-d25f68b951fc)

![Screenshot_2024-09-22-16-24-18-069_com.miui.securitycenter.jpg](https://github.com/user-attachments/assets/fc4b5837-edaf-4405-83d2-5231e381f087)



都给了，依然不行

**Comment by menalssi** [comment]
电脑端防火墙的问题，设置页面最下方的修复防火墙，点一下就可以了。

**Comment by bbggkk** [comment]
> 电脑端防火墙的问题，设置页面最下方的修复防火墙，点一下就可以了。

确认问题了 家里路由是opwrt系统的，2.4G和5Gwifi频段是分开的，2.4G可以传,5G不行，就酱吧
