### ISSUE TITLE
Open source iOS & Android Apps?

### ISSUE THREAD

**Issue by pateljoel** [LANDrop/LANDrop#23]
I saw this in the README:
> Cross platform: when we say it, we mean it. iOS, Android, macOS, Windows, Linux, name yours.

I was looking to contribute to this since I have some ideas I would like to see in LANDrop, (great project btw), so I had a look in the repo but I don't see iOS and Android in there, but I do see them in the app stores.

Are there any plans to open source the iOS & Android apps?

**Comment by mid-kid** [comment]
Was going to ask this as well. I tend to look for the source code of anything that claims to be open.

**Comment by yvbbrjdr** [comment]
1. I did not claim anywhere that LANDrop is free (as in free software) or open source. The desktop version is open sourced as a courtesy.
2. We don't have plans to open source the mobile version, as we plan to monetize it some time in the future.

**Comment by mid-kid** [comment]
Fair enough. I guess I misinterpreted the giant "source code" button on the front page.
