### ISSUE TITLE
Bluetooth?

### ISSUE THREAD

**Issue by midzelis** [LANDrop/LANDrop#24]
I know this is called 'LANdrop' but what if your phones are not on the same LAN, but are close to each other. Could you add the ability to use bluetooth to do the filetransfer? 

My use case is ... I'm at a b-day party or other group event, and everyone has been taking photos/videos. Would love to have an easy way to share (full-size) photos/videos which each other. Whatsapp/Messenger etc all reduce quality of the photos when they sent them. 

Bonus if you could somehow create a p2p bucket --where everyone can dump their files into, and everyone sync's to each other, as long as one client has a copy of all the files. Almost like an instant torrent, but whose contents can change dynamically. 

Just my crazy ideas....

**Comment by yvbbrjdr** [comment]
If you don't have a WLAN because you are outside, you can try to enable your phone's personal hotspot and let your friends connect to it. LANDrop works on that too and it doesn't consume any data. The reason I don't support Bluetooth is it's really slow.. like, about 30 times slower...
