### ISSUE TITLE
"Your system needs to support tray icon." error on startup

### ISSUE THREAD

**Issue by thomaseizinger** [LANDrop/LANDrop#27]
Just installed LANDrop through AUR and getting the above error on launch.

I am on Manjaro Linux with Gnome DE (3.38).

Any pointers on how to fix this?

**Comment by yvbbrjdr** [comment]
Install and enable https://aur.archlinux.org/packages/gnome-shell-extension-tray-icons/

LANDrop requires tray icon to work.

**Comment by thomaseizinger** [comment]
Thanks for the quick response!

Doesn't fix my issue unfortunately. I tried logout / login after the installing and even a full system reboot but the error still appears.

**Comment by yvbbrjdr** [comment]
Did you enable the plugin?

**Comment by thomaseizinger** [comment]
Thanks, that fixed the issue.
