### ISSUE TITLE
About Errno: 13

### ISSUE THREAD

**Issue by Kisaragishin618** [LANDrop/LANDrop#3]
![image](https://user-images.githubusercontent.com/84716066/119342966-5fb34f80-bcc8-11eb-9d87-148dc67a3435.png)
device: Pixelbook 2017
CPU: Intel i5 7y54
program version: 0.1.2
android version: Android 9
Chrome OS version: 90.0.4430.215
可以的话请用中文回复，谢谢

**Comment by yvbbrjdr** [comment]
Try the new 0.1.4 version for Android and see if the problem persists?

**Comment by yvbbrjdr** [comment]
Resolved in 0.1.4. Closing.
