### ISSUE TITLE
To run the AppImage, glibc_2.30 is needed but not present on the Stable Debian !

### ISSUE THREAD

**Issue by Moshe101** [LANDrop/LANDrop#36]
Can you release an AppImage but for qlibc_2.28 which current in Stable Debian ??

Thanks.

**Comment by yvbbrjdr** [comment]
See [README.md](https://github.com/LANDrop/LANDrop/blob/master/README.md):
> The AppImage we provide as the prebuilt for Linux might not work on your machine. You can build LANDrop by yourself if the prebuilt doesn't work for you.
