### ISSUE TITLE
Error in Ubuntu (Could not load the Qt platform plugin "xcb")

### ISSUE THREAD

**Issue by hibetterheyj** [LANDrop/LANDrop#4]
- platform: Ubuntu18.04
- error

When executing the `AppImage`, I encountered the following error:
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```

Thanks for your great work and looking forward to your suggestions!

**Comment by yvbbrjdr** [comment]
hmm you can probably try to build it yourself on Linux? You'll need Qt 5 and libsodium and that's all.

**Comment by kevinwenyu** [comment]
any instruction to build the app under linux.

**Comment by yvbbrjdr** [comment]
Coming soon in the docs

**Comment by yvbbrjdr** [comment]
Build instructions added to readme.

**Comment by sonichy** [comment]
Same error in Deepin 20.2.1
