### ISSUE TITLE
[Features] Manually set the port

### ISSUE THREAD

**Issue by axionl** [LANDrop/LANDrop#5]
> https://doc.qt.io/qt-5/qtcpserver.html#listen
Tells the server to listen for incoming connections on address address and port port. If port is 0, a port is chosen automatically. If address is QHostAddress::Any, the server will listen on all network interfaces.

**Comment by yvbbrjdr** [comment]
Fixed in 6a5da9b628403e7aefe23e2dc1d7b96e96665238
