### ISSUE TITLE
[Bug] Port 52637 binding error

### ISSUE THREAD

**Issue by yDqnnP** [LANDrop/LANDrop#7]
Erorr message pop up when opening the app: 无法绑定端口 52637。你的设备将无法被发现。

**Comment by yDqnnP** [comment]
> Can you make sure that your system is running only 1 instance of LANDrop?

I'm not sure. This issue was gone after a system reboot.

**Comment by UlysessWeb** [comment]
The same problem. And I'm sure that the system is running only 1 instance of LANDrop. Moreover, I check the system ports and make sure that no other app ocuppied the port 52637.

**Comment by eamon2003** [comment]
> The same problem. And I'm sure that the system is running only 1 instance of LANDrop. Moreover, I check the system ports and make sure that no other app ocuppied the port 52637.同样的问题。我确定系统只运行了一个LANDrop实例。此外，我检查了系统端口，并确保没有其他应用程序占用端口52637.

same
