### ISSUE TITLE
Discovery service unavailable in iOS if AdGuard is being used within LAN as DNS server

### ISSUE THREAD

**Issue by illnino** [LANDrop/LANDrop#9]
## ENV

iOS: 14.5.1
Model: iPhone X
iOS App: Ver 0.1.1

## Problem

Discovery service unavailable in iOS if AdGuard is being used within LAN as DNS server.
However, Android has no problem when using AdGuard as DNS server.

In iOS, if Router is chosen as DNS server (e.g. 192.168.1.1), it would work. 

Thanks.

**Comment by isrtest** [comment]
Interesting. Today when I open the app. The alert is no longer shown. I could send files on my iPhone X.

I cant reproduce the issue now. Sorry for the trouble.

**Comment by illnino** [comment]
Interesting. Today when I open the app. The alert is no longer shown. I could send files on my iPhone X.

I cant reproduce the issue now. Sorry for the trouble.
